name:  Static Analysis
on: [push, pull_request]
jobs:
  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      pull-requests: read
    steps:
      - name: Clone
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: cpp
          queries: security-and-quality
          debug: true
      - name: Install bc-crypto-base
        run: |
          cd deps/bc-crypto-base
          ./configure
          make
          sudo make install
      - name: Install bc-shamir
        run: |
          cd deps/bc-shamir
          ./configure
          make
          sudo make install
      # CodeQL will create the database during the compilation
      - name: Build bc-sskr
        run: |
          ./configure
          make
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
  scan_build:
    name: Clang Static Analyzer
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
      statuses: write
    steps:
      - name: Clone
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install clang-tools
        run: |
          sudo apt-get update
          sudo apt-get install clang-tools
      - name: Install bc-crypto-base
        run: |
          cd deps/bc-crypto-base
          ./configure
          make
          sudo make install
      - name: Install bc-shamir
        run: |
          cd deps/bc-shamir
          ./configure
          make
          sudo make install
      - name: Configure bc-sskr
        run: |
          scan-build ./configure
      - name: Build with Clang Static Analyzer
        run: |
          make clean
          scan-build --keep-cc -analyze-headers -enable-checker security -enable-checker unix -enable-checker valist -sarif -o output-scan-build --status-bugs make lib
      - name: Upload scan result
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: output-scan-build
